#farmoutAnalysisJobs DMHistosSpring15_2/ggZH_HToBB_ZToNuNu_M120_13TeV_powheg_pythia8  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/khurana/ggZH_HToBB_ZToNuNu_M120_13TeV_powheg_pythia8/crab_ggZH_HToBB_ZToNuNu_M120_13TeV_powheg_pythia8/150702_105011/0000/ /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/ /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/src/RKGlobalAnalyzer/main.exe --fwklite --input-files-per-job=1

#farmoutAnalysisJobs DMHistosSpring15_2/TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/khurana/TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/crab_TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/150627_090333/0000/ /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/ /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/src/RKGlobalAnalyzer/main.exe --fwklite --input-files-per-job=1

#farmoutAnalysisJobs DMHistosSpring15_2/QCD_Pt-15TTo7000_TuneZ2star-Flat_13TeV_pythia6  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/khurana/QCD_Pt-15TTo7000_TuneZ2star-Flat_13TeV_pythia6/crab_QCD_Pt-15TTo7000_TuneZ2star-Flat_13TeV_pythia6/150702_105050/0000/ /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/ /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/src/RKGlobalAnalyzer/main.exe --fwklite --input-files-per-job=1

#farmoutAnalysisJobs DMHistosSpring15_2/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/khurana/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/crab_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/150629_103219/0000/ /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/ /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/src/RKGlobalAnalyzer/main.exe --fwklite --input-files-per-job=1

#farmoutAnalysisJobs DMHistosSpring15_2/Signal  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/khurana/Signal  /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/ /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/src/RKGlobalAnalyzer/main.exe --fwklite --input-files-per-job=1

farmoutAnalysisJobs DMHistosSpring15_2/WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/khurana/WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/crab_WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/150629_103123/0000/  /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/ /afs/hep.wisc.edu/cms/khurana/DMRunII/CMSSW_7_4_5/src/RKGlobalAnalyzer/main.exe --fwklite --input-files-per-job=1
