for which in MonoHFatJetAnalysis_ForAn_AllMETTriggers_WithBTagScaleFactors_WithPU_WithLooseID_NewTTBar_Exactly1_TightMuonID_LooseBTAG MonoHFatJetAnalysis_ForAn_AllMETTriggers_WithBTagScaleFactors_WithPU_WithLooseID_NewTTBar_Exactly1_TightMuonID_MediumBTAG MonoHFatJetAnalysis_ForAn_AllMETTriggers_WithBTagScaleFactors_WithPU_WithLooseID_NewTTBar_Exactly1_TightMuonID_TightBTAG; 
do
    python RMStackFactory_ratio_Raman_WithStackError.py $which
done